'use strict';
const fullName = 'Jody Clark';
const isCool = false;
const totalPets = 1;
console.log('value of fullName: ', fullName);
console.log('value of isCool: ', isCool);
console.log('value of totalPets: ', totalPets);
console.log('type of fullName: ', typeof fullName);
console.log('type of isCool: ', typeof isCool);
console.log('type of totalPets: ', typeof totalPets);
const empty = null;
console.log('value of null: ', empty);
console.log('type of null: ', typeof empty);
let nothing;
console.log('value of nothing: ', nothing);
console.log('type of nothing: ', typeof nothing);
