'use strict';
const width = 4;
const height = 9;
const area = width * height;
console.log('value of area: ', area);
console.log('type of area: ', typeof area);
const bill = 75;
const payment = 100;
const change = payment - bill;
console.log('value of change: ', change);
console.log('type of change: ', typeof change);
const quizzes = 85;
const midterm = 95;
const final = 93;
const grade = (quizzes + midterm + final) / 3;
console.log('value of grade: ', grade);
console.log('type of grade: ', typeof grade);
const firstName = 'Jody';
const lastName = 'Clark';
const fullName = firstName + ' ' + lastName;
console.log('value of fullName: ', fullName);
console.log('type of fullName', typeof fullName);
const pH = 7.3;
const isAcidic = pH < 7;
console.log('value of isAcidic: ', isAcidic);
console.log('type of isAcidic: ', typeof isAcidic);
const headCount = 150;
const isSparta = headCount === 300;
console.log('value of isSparta: ', isSparta);
console.log('type of isSparta: ', typeof isSparta);
let motto = fullName;
motto += ' is the GOAT';
console.log('value of motto: ', motto);
console.log('type of motto: ', typeof motto);
